services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-payment-app
    container_name: product_payment_app
    volumes:
      - .:/var/www/product-payment-app
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8337:80"
    volumes:
      - .:/var/www/product-payment-app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  database:
    image: mysql:latest
    container_name: mysql_db_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
